# Generated by Django 3.1.3 on 2020-12-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoninfo',
            name='IdNum',
            field=models.IntegerField(),
        ),
    ]
