# Generated by Django 3.1.3 on 2020-12-19 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdapi', '0003_auto_20201218_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressId', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=65)),
                ('province', models.CharField(max_length=65)),
                ('city', models.CharField(max_length=65)),
                ('zipCode', models.CharField(max_length=65)),
                ('addressLine1', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Allergies',
            fields=[
                ('allergiesId', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('symptoms', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostics',
            fields=[
                ('diagnosticsId', models.CharField(max_length=8, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticsDesc',
            fields=[
                ('diagnosticsDescId', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('cause', models.TextField()),
                ('symptomsDesc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('examId', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('examType', models.CharField(max_length=250)),
                ('date', models.DateTimeField()),
                ('diagnosticsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdapi.diagnostics')),
            ],
        ),
        migrations.CreateModel(
            name='PregnancyComplications',
            fields=[
                ('complicationId', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('complication', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescriptionId', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('prescribedMeds', models.CharField(max_length=100)),
                ('usage', models.CharField(max_length=50)),
                ('prescribedAmount', models.CharField(max_length=10)),
                ('start', models.DateTimeField()),
                ('finish', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sickness',
            fields=[
                ('sicknessId', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('illness', models.CharField(max_length=100)),
                ('symptoms', models.CharField(max_length=100)),
                ('chronic', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctorId',
            field=models.CharField(blank=True, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='commoninfo_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='pdapi.commoninfo'),
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('treatmentId', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=100)),
                ('prescriptionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdapi.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='SergicalRecord',
            fields=[
                ('sergicalRecordId', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('sergType', models.CharField(max_length=50)),
                ('progressReport', models.TextField(max_length=5000)),
                ('operationDate', models.DateTimeField()),
                ('diagnosticsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdapi.diagnostics')),
                ('doctorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdapi.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='ObstericsRecord',
            fields=[
                ('obstericRecordId', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('pregnancies', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('complicationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdapi.pregnancycomplications')),
                ('diagnosticsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdapi.diagnostics')),
                ('doctorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdapi.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='MedRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergiesId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdapi.allergies')),
                ('diagnosticsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdapi.diagnostics')),
                ('examsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdapi.exam')),
                ('obstrericId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdapi.obstericsrecord')),
                ('sergicalRecordId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdapi.sergicalrecord')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='doctorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdapi.doctor'),
        ),
        migrations.AddField(
            model_name='diagnostics',
            name='diagnosticsDescId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdapi.diagnosticsdesc'),
        ),
        migrations.AddField(
            model_name='diagnostics',
            name='doctorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdapi.doctor'),
        ),
        migrations.AddField(
            model_name='diagnostics',
            name='sicknessId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdapi.sickness'),
        ),
        migrations.AddField(
            model_name='diagnostics',
            name='treatmentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdapi.treatment'),
        ),
        migrations.AddField(
            model_name='allergies',
            name='diagnosticsId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdapi.diagnostics'),
        ),
    ]
